AWSTemplateFormatVersion: 2010-09-09
Description: https://hackathon2023-public.s3.amazonaws.com/2023-04/tls-app-deployer.yaml

Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  AppName:
    Type: String
    Description: Name used to identify the application
    Default: test-container
  TLSPCAPIKey:
    Type: String
    Description: From https://ui.venafi.cloud/platform-settings/user-preferences?key=api-keys
    NoEcho: true
  CAName:
    Type: String
    Description: The name of the Certificate Authority you want to use in TLS Protect Cloud
    Default: BUILTIN

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  VenafiCertLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Role: !GetAtt LambdaRole.Arn
      Handler: venafi-cert-lambda.lambda_handler
      Timeout: 90 
      Code:
        S3Bucket: hackathon2023-public
        S3Key: 2023-04/venafi-cert-lambda.zip
          

  VenafiCustomCertResource:
    Type: Custom::VenafiCert
    DependsOn: VenafiCertLambda
    Properties:
      ServiceToken: !GetAtt VenafiCertLambda.Arn
      TLSPCAPIKey: !Ref TLSPCAPIKey
      AppName: !Ref AppName
      CAName: !Ref CAName
      TemplateName: !Ref TemplateName
      CertCommonName: !Ref CommonName


Outputs:
  Certificate:
    Value: !GetAtt VenafiCustomCertResource.Certificate
    Description: The certificate returned from TLS Protect Cloud

  CertificateChain:
    Value: !GetAtt VenafiCustomCertResource.Chain
    Description: The certificate chain returned from TLS Protect Cloud

  CertificatePrivateKey:
    Value: !GetAtt VenafiCustomCertResource.PrivateKey
    Description: The private key returned from TLS Protect Cloud

  DomainName:
    Value: !Join ["", [!Ref AppName, ".com"]]
    Description: The URL associated with the certificate

  URL:
    Value: !Join ["", ["https://", !Ref AppName, ".com"]]
    Description: The URL of the endpoint using the certificate
