version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bash-hello"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1stwh7l679mcf"
s3_prefix = "bash-hello"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
