AWSTemplateFormatVersion: '2010-09-09'
Description: https://venafi-ecosystem.s3.amazonaws.com/tlspc/templates/bash-hello.yaml
Resources:
  BashHelloFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Sub venafi-ecosystem-${AWS::Region}
        S3Key: tlspc/functions/bash-hello.zip
      FunctionName: bash-hello
      Handler: app.handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/AWSLambdaBasicExecutionRole
      Runtime: provided
  BashHelloResource:
    Type: "Custom::BashHello"
    Properties:
      ServiceToken: !GetAtt BashHelloFunction.Arn