AWSTemplateFormatVersion: '2010-09-09'
Description: https://venafi-ecosystem.s3.amazonaws.com/tlspc/templates/do-nothing.yaml

Parameters:
  TLSPCAPIKey:
    Type: String
    Description: From https://ui.venafi.cloud/platform-settings/user-preferences?key=api-keys
    NoEcho: true

Resources:
  DoNothingFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Sub venafi-ecosystem-${AWS::Region}
        S3Key: tlspc/functions/do-nothing.zip
      Handler: app.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/VenafiEcosystemLambdaBasicExecutionRole
      Runtime: python3.10
  DoNothingResource:
    Type: "Custom::DoNothing"
    Properties:
      ServiceToken: !GetAtt DoNothingFunction.Arn
      TLSPCAPIKey: !Ref TLSPCAPIKey

Outputs:
  Message: 
    Value: !GetAtt DoNothingResource.message