AWSTemplateFormatVersion: '2010-09-09'
Description: https://venafi-ecosystem.s3.amazonaws.com/tlspc/templates/tlspc-application.yaml
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Application Properties
        Parameters:
          - AppName
          - AppDescription
          - IssuingTemplateName
          - CertificateAuthority
      - Label:
          default: Credentials
        Parameters:
          - TLSPCAPIKey

Parameters:
  TLSPCAPIKey:
    Type: String
    Description: Obtained from https://ui.venafi.cloud/platform-settings/user-preferences?key=api-keys
    ConstraintDescription: TLSPCAPIKey must be structured as xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx and contain only lowercase hex-letters and numbers
    AllowedPattern: "[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}"
    NoEcho: true
  AppName:
    Type: String
    Description: As shown at https://ui.venafi.cloud/certificate-issuance/applications
  AppDescription:
    Type: String
    Description: As shown at https://ui.venafi.cloud/certificate-issuance/applications
  IssuingTemplateName:
    Type: String
    Description: As shown at https://ui.venafi.cloud/certificate-issuance/issuing-templates
    Default: Default
  CertificateAuthority:
    Type: String
    Description: As shown at https://ui.venafi.cloud/certificate-issuance/issuing-templates
    Default: BUILTIN
    AllowedValues:
      - ACME
      - BUILTIN
      - DIGICERT
      - ENTRUST
      - GLOBALSIGN
      - GLOBALSIGNMSSL
      - MICROSOFT
      - TPP
      - ZTPKI

Resources:
  TLSPCApplicationFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub venafi-ecosystem-${AWS::Region}
        S3Key: tlspc/functions/tlspc-application.zip
      Handler: app.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/VenafiLambdaBasicExecutionRole
      Runtime: python3.10
      Timeout: 60
  TLSPCApplicationResource:
    Type: Custom::TLSPCApplication
    Properties:
      ServiceToken: !GetAtt TLSPCApplicationFunction.Arn
      TLSPCAPIKey: !Ref TLSPCAPIKey
      AppName: !Ref AppName
      AppDescription: !Ref AppDescription
      IssuingTemplateName: !Ref IssuingTemplateName
      CertificateAuthority: !Ref CertificateAuthority

Outputs:
  IssuingTemplateId:
    Value: !GetAtt TLSPCApplicationResource.IssuingTemplateId