AWSTemplateFormatVersion: '2010-09-09'
Description: https://venafi-ecosystem.s3.amazonaws.com/tlspc/templates/tlspc-certificate.yaml
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Certificate Properties
        Parameters:
          - Zone
          - CommonName
      - Label:
          default: Credentials
        Parameters:
          - TLSPCAPIKey
      - Label:
          default: System
        Parameters:
          - RenewalTrigger

Parameters:
  TLSPCAPIKey:
    Type: String
    Description: From https://ui.venafi.cloud/platform-settings/user-preferences?key=api-keys
    ConstraintDescription: TLSPCAPIKey must be structured as xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx and contain only lowercase hex-letters and numbers
    AllowedPattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
    NoEcho: true
  Zone:
    Type: String
    Description: Zones are logical organizational units used for managing digital certificates. Typical form is <AppName>\<IssuingTemplateAlias>
    ConstraintDescription: Typical form is <AppName>\<IssuingTemplateAlias>
    AllowedPattern: ^.*\\.*$
    Default: ExampleApp\Default
  CommonName:
    Type: String
    Description: The subject/domain of the certificate
    ConstraintDescription: For example www.example.com
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    Default: www.example.com
  RenewalTrigger:
    Type: String
    Description: PLEASE IGNORE - parameter is reserved for internal use

Resources:
  TLSPCCertificateFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub venafi-ecosystem-${AWS::Region}
        S3Key: tlspc/functions/tlspc-certificate.zip
      Handler: app.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/VenafiLambdaBasicExecutionRole
      Runtime: python3.10
      Timeout: 60
  TLSPCCertificateResource:
    Type: Custom::TLSPCCertificate
    Properties:
      ServiceToken: !GetAtt TLSPCCertificateFunction.Arn
      TLSPCAPIKey: !Ref TLSPCAPIKey
      Zone: !Ref Zone
      CommonName: !Ref CommonName
      RenewalTrigger: !Ref RenewalTrigger

Outputs:
  Message: 
    Value: !GetAtt TLSPCCertificateResource.message
  LatestCertId:
    Value: !GetAtt TLSPCCertificateResource.LatestCertId