AWSTemplateFormatVersion: '2010-09-09'
Description: https://venafi-ecosystem.s3.amazonaws.com/tlspc/templates/tlspc-policy.yaml
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Policy Properties
        Parameters:
          - Zone
          - CertificateAuthority
          - MaxValidDays
          - Domains
      - Label:
          default: Credentials
        Parameters:
          - TLSPCAPIKey

Parameters:
  TLSPCAPIKey:
    Type: String
    Description: API Key from https://ui.venafi.cloud/platform-settings/user-preferences?key=api-keys
    ConstraintDescription: TLSPCAPIKey must be structured as xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx and contain only lowercase hex-letters and numbers
    AllowedPattern: "[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}"
    NoEcho: true
  CertificateAuthorityProduct:
    Type: String
    Description: As derived when building https://ui.venafi.cloud/certificate-issuance/issuing-templates, in the format of <CA_PROVIDER>\<CA_TLSPC_NAME>\<CA_PRODUCT_OPTION>. Refer to documentation for further details.
    ConstraintDescription: In the format of <CA_PROVIDER>\<CA_TLSPC_NAME>\<CA_PRODUCT_OPTION>
    AllowedPattern: ".*\\\\.*\\\\.*"
    Default: "BUILTIN\\Built-In CA\\Default Product"
  Zone:
    Type: String
    Description: Zones are logical organizational units used for managing digital certificates. Typical form is <AppName>\<CertificateIssuingTemplateAlias>.
    ConstraintDescription: Typical form is <AppName>\<CertificateIssuingTemplateAlias>
    AllowedPattern: ^.*\\.*$
    Default: phoenix-app\phoenix-cit
  MaxValidDays:
    Type: Number
    Description: The maximum number of days for which any created/renewed certificate is considered valid.
    ConstraintDescription: A positive, non zero number
    MinValue: 1
    Default: 90
  Domains:
    Type: List<String>
    Description: A comma-separated list of domain names considered valid in the context of this policy
    ConstraintDescription: A comma-separated list, for example "foo.com,bar.org"
    AllowedPattern: ^[a-zA-Z0-9]+([\-]{1}[a-zA-Z0-9]+)*([\.]{1}[a-zA-Z0-9]+([\-]{1}[a-zA-Z0-9]+)*)*$
    Default: "example.com"

Resources:
  TLSPCPolicyFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub venafi-ecosystem-${AWS::Region}
        S3Key: tlspc/functions/tlspc-policy.zip
      Handler: app.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/VenafiLambdaBasicExecutionRole
      Runtime: python3.10
      Timeout: 60
  TLSPCPolicyResource:
    Type: Custom::TLSPCPolicy
    Properties:
      ServiceToken: !GetAtt TLSPCPolicyFunction.Arn
      CertificateAuthorityProduct: !Ref CertificateAuthorityProduct
      Zone: !Ref Zone
      MaxValidDays: !Ref MaxValidDays
      Domains: !Ref Domains
      TLSPCAPIKey: !Ref TLSPCAPIKey

Outputs:
  CertificateIssuingTemplateId:
    Value: !GetAtt TLSPCPolicyResource.CertificateIssuingTemplateId
  ApplicationId:
    Value: !GetAtt TLSPCPolicyResource.ApplicationId
  CertificateIssuingTemplatePolicy:
    Value: !GetAtt TLSPCPolicyResource.CertificateIssuingTemplatePolicy
