AWSTemplateFormatVersion: "2010-09-09"
Description: https://venafi-ecosystem.s3.amazonaws.com/tlspc/templates/venafi-ecosystem-setup.yaml
Resources:
  VenafiEcosystemLambdaBasicExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: VenafiEcosystemLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
