name: Zip and Upload Python to S3

on:
  push:
    paths:
      - 'lambda/**/*.py'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y zip

    - name: Upload Python files
      run: |
        for file in lambda/*.py; do
          aws s3 cp "$file" s3://venafi-ecosystem/templates/
        done

