name: tlspc-upload-cfn-templates

on:
  push:
    branches:
      - main
    paths:
      - 'tlspc/templates/**'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.2.0
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload CloudFormation templates
      run: |
        s3_bucket=venafi-ecosystem
        s3_prefix=tlspc/templates
        pushd . > /dev/null
        cd tlspc/templates/
        for template in *.yaml; do
          echo "found ${template}"
          aws s3 cp ${template} s3://${s3_bucket}/${s3_prefix}/${template}
        done
        popd > /dev/null
